### ISSUE TITLE
Armor Stands and Hostile Mobs are displayed in /asadmin topbreeders

### ISSUE THREAD

**Issue by Zachar543** [tastybento/askyblock#15]
/asadmin topbreeders displays all entities that inherit from LivingEntity, which includes Armor Stands and all hostile mobs.
![asadmin topbreeders](https://cloud.githubusercontent.com/assets/2058925/6607420/0abc0f5c-c815-11e4-9f7d-c7aacccbe5d4.png)

Side note: It seems that throwing chicken eggs can get you over the default limit of 25, yet breeding limit messages start way before 25 if you have armor stands.

**Comment by tastybento** [comment]
Cheers. This was semi by-design - I wanted to see all the monsters too. However, ArmorStands are silly. I've changed the filtering to be Creatures as that does capture hostile mobs which can be farmed too.

For the breeding limit - this is a bug, but in the reporting. The warning was going out too early to players and yes, it was based on all entities on the island, so wrong. This was not actually stopping animals from spawning if the true animal limit was not breached, that's why you probably saw eggs still working. But now it's all fixed. See the 2.8.9 branch for the fix.
