### ISSUE TITLE
Setting island level upon new island

### ISSUE THREAD

**Issue by TWSSYesterday** [tastybento/askyblock#161]
Is there/could there be an option where we can set the starting level of islands? For example, I changed my default island and the starting level is 151. Could we use an option in the island setting's section of the config to do this? 
Thanks

**Comment by tastybento** [comment]
Interesting idea. It is more difficult that it sounds because each island schematic would need a different handicap and right now, after the island is made, the schematic info is not stored anywhere. It would have to be stored somewhere specific to the island because players can come and go. Hmmm, I'll have to think about this.

**Comment by slkjoy** [comment]
Maybe you can set a multiplier for each schematic that is used in calculating the island level – i.e. multiply the block values by this number. For example, 0.5 would halve the block values used for that island. 2.0 would double the block values. It's rather crude, but maybe simple to implement? Not sure how this factors in setting the multiplier for blocks below sea level (does it override?).

**Comment by tastybento** [comment]
Done in 	b0b73cd
