### ISSUE TITLE
Lava Fire Spread Enabled?

### ISSUE THREAD

**Issue by philip-ulrich** [tastybento/askyblock#205]
I have Lava Fire Spread disabled in Essentials, but on my islands.. lava still starts fires. I don't see an option in the config for that in ASB, but I see other fire spreads listed (and they are disabled). Could it be ASB causing the fires?

I'm on Spigot 1.9.2 and A Skyblock 3.0.0.1. I don't see these fires on my "spawn world" so it makes me suspect it's ASB.

**Comment by tastybento** [comment]
I can't find a problem. I tested with Essentials fire spread on and off and ASB on and off and it worked as expected. ASB never un-cancels an event. It only ever cancels one, so I'm not sure how it would be possible for ASB to override Essentials. It could be another plugin maybe, I don't know, sorry.

**Comment by philip-ulrich** [comment]
I'll keep looking into it. Thanks for the quick response.

**Comment by philip-ulrich** [comment]
It can take a while to happen. You can see my set up and it occurring in this video. I'm going to shut off all plugins except ASB and do another vid. See if it still happens.

http://d.l33t.tech/13w8i/2MDEic2w

**Comment by philip-ulrich** [comment]
I hate to say it, but it looks like it's ASB. 

http://d.l33t.tech/1fzAe/7ubuzUio

The only thing that is enabled is a slack integrator (forwards chats), a plugin integrator (sends plugin info to a control panel), vault, Pex and ASB.

**Comment by tastybento** [comment]
Ah, yes I see what's going on. The lava is igniting the block next to it. I don't actually stop ignition, just spreading (and the associated burning) so this was slipping through. You can see this because if fire is allowed, but fire spread is off, then you can use flint steel to set fire to stuff - it just won't burn or spread. I can see how lava ignition can be perceived as a spread though (the lava is kind of like fire) so I've added some code to the next version that will stop this.

**Comment by philip-ulrich** [comment]
That's what I was getting at. I believe essentials "stop lava fire spread" or w/e it is keeps this from happening (which is why it doesn't happen in my spawn world), but in this case it looks like your plugin overrides those guards and sets it's own. Lava fire spread being one not addressed. 

Thanks for fixing it!

**Comment by tastybento** [comment]
Will be fixed in 3.0.0.4
