### ISSUE TITLE
Updated server to 1.9.2, using 3.0.0.3

### ISSUE THREAD

**Issue by TNTUP** [tastybento/askyblock#206]
Hi, I've encountered something urgent which causes players to have their inventory on login. I've updated the server today and I saw my inventory reset. 

I suspect Askyblock and Acidisland, I've removed them, restarted server, loaded my second account and his inventory not reset. Reloading up them/restarting server, I log my second account, inventory reset!

I have removed them for now and no inventory reset issues! While loading them up, it happens! There's no errors or whatever, no such debug options or its a different name? I hope you can solve my issue, this is quite important :/

EDIT: Seems 3.0.0.3 overrides the login event so Essentials/PWI or other are ignored. 

Without AI: Logs in their last position as normal
With AI: Logs in a different location (the spawn) and triggered as a new player but isn't. 

Same for SB. They take over about PlayerLoginEvent or somesort of playerjoin handler?

**Comment by tastybento** [comment]
Do you have pushing set to off?

**Comment by tastybento** [comment]
If so, try setting it to allow and see if you still have a problem.

**Comment by tastybento** [comment]
Also, try this version to see if it makes any difference:

https://github.com/tastybento/askyblock/releases/tag/V3.0.0.4

**Comment by TNTUP** [comment]
@tastybento How pushing can be an issue? :P I'll try this on a test server^^

**Comment by tastybento** [comment]
The only code I added around joining is to prevent pushing. The only API to do that is to set scoreboard flags. This could be interfering.

**Comment by TNTUP** [comment]
Okay, weird...I'll try this enabled and return the results

**Comment by TNTUP** [comment]
Enabled it, still occurs. I remove ASkyblock, my inventory is back to normal and last location. Reenabling it, I have a different inventory and location.

**Comment by tastybento** [comment]
So, what plugin are you using to manage inventories?

**Comment by TNTUP** [comment]
I'm using PerWorldInventory, it never happened in 1.8.8, so I don't see as an issue with it.

Also, the PWI plugin was removed because my tests were done. I'll try with Askyblock only.

**Comment by TNTUP** [comment]
I did a video about my issue if you want to look: https://www.youtube.com/watch?v=WUNY3yuGOlw 

Waiting PlotSquared's devs to answer :)

**Comment by TNTUP** [comment]
@tastybento I noticed on a fresh install that in AcidIsland world folder, in playerdata's theres files in it which isn't supposed to happen. ASkyblock doesn't have an inventory. I tried ASkyblock too and does the same aswell when PlotSquared is enabled. IS there a way to prevent ASkyBlock/AcidIsland doing this while PlotSquared is running? Didn't happen in 1.8.8.

**Comment by tastybento** [comment]
That folder is used by the server to store player files and would only contain anything if you set the main server world to ASkyBlock or AcidIsland in server.properties.

When you say "fresh install" please define exactly what you mean: A fresh install would use world/world_nether/world_the_end as the default world.

**Comment by TNTUP** [comment]
I mean by fresh install, Multiverse-Core, PlotSquared, AcidIsland and ASkyblock. In 1.8.8, ASkyblock or Acid never stores playerdata in that folder in their world. You can even reproduce that issue on a test server on your end.

In 1.9.2, When PlotSquared is enabled, Either AcidIsland or ASkyblock saves inventory in AcidIsland/playerdata instead than loading in world/playerdata which this isn't supposed to happen. I've did a video about this. Mind watching it and replicate on your side? I had to disable worlds due to this issue :/

**Comment by tastybento** [comment]
There's something weird going on with the initial install of P2. My experience:

1. Clean install - new 1.9.2 server (latest, well 5 versions behind) - new EULA, the whole bit - start clean, then stop server
2. Install Vault (latest) and ASkyBlock (latest) to plugins.
3. Start server.
4. Log in. In the default world.
5. Do /island and start and island. Grab some items from the chest. 
6. Log out in ASkyBlock world.
7. Shutdown server - look in ASkyBlock/playerdata folder - it's empty.
8. Install PlotSquared to plugins
9. Start server, console log looks good, no errors.
10. Log in - I am now in world, and I have no items. There is now a file in ASkyBlock/playerdata for my player.
11. Do /island and grab some stuff.
12. Log out
13. Log back in and I am still on my island and have my stuff.
14. Have another player log in, start island, grab stuff. Log out.
15.Restart server
16. Players log in - everything seems to work.

Conclusion: Installing P2 for the first time deletes player's inventories. Once it's installed, it seems to work okay.

I need to head off now, but I'll see if there's something going on with that initial install. I suspect it's because both plugins load at startup and maybe ASkyBlock doesn't get to register its world or something.

**Comment by TNTUP** [comment]
Have you tried removing P2? It will revert to your normal inventory/location.

**Comment by tastybento** [comment]
Yes, if I remove it, I get back my inventory and go back to the previous position. It appears that P2 puts the player saves in the world folder for some reason. That's why when a player who is ASkyBlock logs in the server after P2 is installed for the first time, the server looks at the player info folder in ASkyBlock, sees there is nothing there and teleports the player to the main world, where of course they have nothing. If you remove P2, then the server looks for player saves in the default world, finds your info and puts you back in ASkyBlock with your inventory. 

Weird. Once P2 is installed, it all seems to work, but that initial bit is problematic. Not sure what the solution is right now.

**Comment by TNTUP** [comment]
Yeah, so I've disabled AcidIsland/Askyblock for the time being, sucks I cannot run them at the same time. I'm still waiting for P2's devs to answer

**Comment by TNTUP** [comment]
Removing "load: startup" in the plugin.yml fixes it (AcidIsland/AskyBlock). Closing this issue.

PS: Removing load:startup in P2's does not fix if I kept load: startup in your plugin. Removing "load: startup" in AcidIsland/AskyBlock solves my issue.

**Comment by tastybento** [comment]
Interesting. I think this will only work if you use Multiverse to register the generator, so take care.

**Comment by TNTUP** [comment]
I am using Multiverse-Core^^ I started to see those "Multiverse already knows for generator Acidisland" which is supposed to happen, I remember I've seen that message on startup :)

**Comment by tastybento** [comment]
I found a solution - 

https://github.com/tastybento/askyblock/releases/tag/V3.0.0.4

**Comment by TNTUP** [comment]
I'll give it a run on my test server.

EDIT: yup, no issues now. P2 with ASkyBlock on the same server with this fix solves it! :p
(same inventory/location with/out ASkyblock with P2)

**Comment by tastybento** [comment]
Okay, great. I'll release this now I think.

**Comment by TNTUP** [comment]
I've noticed while I disconnected my other account ([20:52:34 ERROR]: [ASkyBlock] Problem saving name database! Could not rename files!) safe to ignore?

**Comment by tastybento** [comment]
Hmm, you shouldn't see that error

**Comment by tastybento** [comment]
@TNTUP Try this version - it has better cross-platform compatibility: https://github.com/tastybento/askyblock/releases/tag/3.0.0.5
