### ISSUE TITLE
[Potential bug, not sure] Superflat world generation at y1-3. thousands of grass+bedrock.

### ISSUE THREAD

**Issue by iRaiya** [tastybento/askyblock#218]
We've recently found https://proxy.spigotmc.org/46911a9166eab9bf1487ba570c5a3695473e2995?url=http%3A%2F%2Fpuu.sh%2FoBVm6.jpg in our skyblock world (random generated superflat grass+bedrock). 
It's at y=1 ~ 3 , and we're absolutely stumped on where it came from. There's hundreds if not thousands of chunks of this, and I can assure you there was no generation done on this world prior to ASkyBlock being implemented.

I just wanted to ask if this is anything you're familiar with, or anything you may know how to fix. There's a chance an admin ran worldborder's map generation command by mistake on skyblock, but they believe they didn't and I'm not sure if the worldborder generation is that... random.

If you need additional information, or are entirely unable to even begin resolving this, that's perfectly fine. I'm not here to throw blame or expectations at you, just a friendly enquiry from an otherwise confused server.

Sincere thanks for your time,
Rai.

**Comment by tastybento** [comment]
Fundamentally, this is caused by the ASkyBlock generator not running for some reason. Do you use Multiverse? There was a buggy version recently that did not accept generators for worlds. The latest stable version works. A few admins have reported this issue and I saw it myself. You can look through the logs for errors from multiverse, or maybe even from ASkyBlock. It checks if the generator is not running at startup and will disable itself. This won't stop flat chunks from being generated if someone flies around the world though.

**Comment by tastybento** [comment]
I wrote a recovery mode that will auto-fix any super flat chunks. See https://github.com/tastybento/askyblock/releases/tag/3.0.0.6

It'll solve your problem, but only if the ASkyBlock generator is running, so make sure that's the case!

**Comment by iRaiya** [comment]
Hey! Sorry for the delayed response.
Thanks so much for getting back to me and letting me know I'm not losing my marbles!

I've just finished couple days of work so I'll try this when I'm at my PC tomorrow. 

10/10 communication, will recommend to all :)
