### ISSUE TITLE
Permanent Coop

### ISSUE THREAD

**Issue by ghost** [tastybento/askyblock#239]
Ref: https://github.com/tastybento/askyblock/commit/219d17f7aa5a71edc6f7bd3e9b34a81da04370ca

Would like to see the permanent coop handled by a command attribute and not a config entry:
/is coop <player> permanent

**Comment by tastybento** [comment]
Why?

**Comment by meytro** [comment]
It's pretty helpful that there is a command for unexperienced players which removes the build permissions for foreign players if the owner leaves the server. Every large server has problems with griefers and /is coop helps at least a little bit by removing the permissions automatically after the logout.

But I would like to keep the option to make coop permanent for the experienced players who know what they do. That's why I think that the "/is coop <player> permanent" command would be the better solution.

**Comment by tastybento** [comment]
Oh, I see that you mean you want this as a command for players to make. I thought it was a request for the admin to turn it on and off globally.

Hmm, I'll have to think how to do this.

**Comment by Dennisxo** [comment]
Yeah this would be very nice!
But can you make it that a player must have an island and can coop with other islands? for fact to disable partys
