### ISSUE TITLE
SignEdit

### ISSUE THREAD

**Issue by Steev93** [tastybento/askyblock#293]
Hey Tastybento,

Anyway to hook a signedit plugin into Skyblock, as since you don't use worldguard unsure how it may work but it's a question for you

https://dev.bukkit.org/bukkit-plugins/signs/

https://www.spigotmc.org/resources/editablesign-1-7-1-10.2502/

**Comment by tastybento** [comment]
Does this not work? What error do you see? If Villager Trading is enabled on the island, does it work?

**Comment by Steev93** [comment]
Anyone can edit the signs on any island even spawn

**Comment by tastybento** [comment]
Yeah, it looks like those plugins check for WG regions/flags. They'd need to be changed to use the ASkyBlock API.

**Comment by Steev93** [comment]
Send a message to one of the Dev's

Thanks

**Comment by Steev93** [comment]
Hey @tastybento 

Hoping you could help me with this;

http://prntscr.com/dq7d2p
http://prntscr.com/dq7d3p

I am still learning everything, however what would i need to add for aSkyblock to work under the protections

**Comment by tastybento** [comment]
@Steev93 - have a look at https://github.com/tastybento/Signs/releases/tag/2.0

I Mavenized the project - you just need to have all the plugins locally stored in a folder (look at the top of the POM to see where). You won't need ASkyBlock or AcidIsland because they have Maven repositories. Adding support for ASkyBlock and AcidIsland wasn't too hard once I worked out the Maven thing.

**Comment by tastybento** [comment]
I'm going to close this now as I think it's all done.
