### ISSUE TITLE
Askyblock Nether

### ISSUE THREAD

**Issue by Steev93** [tastybento/askyblock#300]
Mob Eggs dont copy over in the chests, they appear blank :L   

Using Worldedit 6.1.3 in the Nether Chests

**Comment by tastybento** [comment]
You mean in the schematics?

**Comment by Steev93** [comment]
Sorry yes, pasting the copy is fine but loading it with everything in the chest's Mob Eggs appear blank.,

The server is running CraftBukkit version git-Spigot-6016ac7-10c10b3 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)

**Comment by Steev93** [comment]
Sorry any updates to this ?

**Comment by tastybento** [comment]
Mob Eggs are not supported in the schematic pasting, sorry.

**Comment by Steev93** [comment]
Okies thanks for this!

Will just have to wait and see it it will be released

**Comment by Steev93** [comment]
@tastybento was this fixed in the latest update I think you said? I am yet to test this however

**Comment by tastybento** [comment]
Spawn Eggs are a mess. Up to 1.8 works. In 1.9, Mojang changed how they worked and Bukkit/Spigot didn't keep up. This is now fixed in the API in 1.11 (which also works for 1.10) but I haven't completely coded to that new API yet. So there is a "hole" where 1.9 is screwed and would need special treatment. 1.11 will get done first and 1.9 might not get done.

**Comment by Steev93** [comment]
@tastybento  Awesome all good thought to bump this and ask cause i saw another thread mentioning you have changed somehting

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#56
