### ISSUE TITLE
./is biome doesn't change all chunks on an island

### ISSUE THREAD

**Issue by roastnewt** [tastybento/askyblock#32]
Sometimes /is biome doesn't change all the chunks on a player's island, just a few of them, or just at the bedrock.

**Comment by tastybento** [comment]
I believe this is just a caching issue. In order to do biome changes efficiently, especially with large islands, the biome change for a block is done only when the chunk is loaded. (Setting the biome can only be done on a block, by block basis, not chunk by chunk). So it could be that the chunk is cached and it won't change until it's unloaded and loaded again. The best way to tell is to find the offending position, teleport to another world and then teleport back, or log out and back in and see if the the biome is set.

If this is not the case, let me know.

**Comment by tastybento** [comment]
One more point, if there is a plugin like Multiverse that keeps blocks around spawn loaded all the time, the biome might not change. So if this is happening around 0,0 or wherever your spawn is, that may be the reason. In that case, the biome will change when the server resets.

**Comment by roastnewt** [comment]
Thanks, I will do some testing!

**Comment by tastybento** [comment]
Did you manage to check it?

**Comment by roastnewt** [comment]
It looks like it was a matter of certain chunks not unloading.  Thanks for your help.
