### ISSUE TITLE
Homestead challenge only recognises an oak door

### ISSUE THREAD

**Issue by steve4744** [tastybento/askyblock#350]
Homestead challenge requires a wooden door to be present. If the door is not the default oak door, e.g. a spruce or birch dooor, the challenge fails "missing 1 x wooden door".
![2016-11-08_01 28 44](https://cloud.githubusercontent.com/assets/6975392/20083413/12c3a5e8-a554-11e6-87a6-b1e501d833b7.png)

**Comment by Poslovitch** [comment]
What should I add?
A sort of required-optionnal items list?

**Comment by tastybento** [comment]
@steve4744 - Yes, unfortunately, Mojang decided to make the different doors different Materials instead of variations on a wooden door. As a work-around, the description of the challenge could be changed to say "Oak door" maybe. 
@Poslovitch To make this generic, we would need some way to specify multiple options items. Maybe something like this (in YML):

# All items listed are required
# If multiple items are listed on the same line, either of the items on that line are allowed
requireditems:
   - BED:1 
   - BOOKSHELF:1
   - WOODEN_DOOR:1, ACACIA_DOOR:1, BIRCH_DOOR:1, SPRUCE_DOOR:1, JUNGLE_DOOR:1

What do you think?

**Comment by Poslovitch** [comment]
It is exactly how I wanted to do.
I'll work on it in my rewrite ;)

**Comment by steve4744** [comment]
Thanks

**Comment by tastybento** [comment]
Handled in #566
