### ISSUE TITLE
Only override nether portal if the other portal is not found on suitable location

### ISSUE THREAD

**Issue by Darker** [tastybento/askyblock#36]
Currently, the nether portals are completelly overidden which results in rather unexpected behavior. Entity transportation is impossible and player has no control over his landing location, which is often quite absurd.

Therefore I'd suggest the nether portal is only overriden if the portal on the other side isn't found. That would keep the protection against invading other islands but would stop the uncomfortable behavior.

**Comment by tastybento** [comment]
Let me clarify a few things. 

You would like the ability to transfer entities through portals? I assume mine carts? I purposely disabled animals because they were causing issues , but I'm willing to look at it again. 

For the portal part I don't completely understand. When going to Nether islands - I assume this is the situation - the portal blocks are not generated in the nether on purpose because otherwise they could become an unlimited source of obsidian. So, only a teleport is made and there never is a portal on the nether side. I suppose the player could build one and then that could be linked. Can you explain your thoughts more here?

**Comment by tastybento** [comment]
Okay, the way I have implemented it is as follows:

1. When player teleports to the Nether from a nether portal in the over world, they will teleport to the closest safe spot in the island nether. A safe spot is basically a solid block with air above it. This means that if a player builds a portal very high up and in the same vicinity as the nether mob island, it is possible to pop out at the top of it.
2. Now, if the player is in the Nether and builds a nether portal themselves, the portals will link up. A portal always has precedence over just a safe spot. This enables players to guide the transfer points themselves.
3. If there are more than one portal, the closest one will be used. This enables multiple portal routes per island.
4. Entities (animals, mobs, carts, items etc,) can now transfer through portals with the new Nether enabled. They will retain their velocity, so it's possible to have mine carts and rails work (with careful design and orientation).
5. Portal and safe spot searching are done async and optimized so even with an 800x800 protection zone, it takes little time to locate. (I don't recommend such a big zone, but I test to it).

**Comment by Darker** [comment]
Hello,
what you described is exactly what I meant - only use teleportation of normal portals are not available. Also are you really sure you need to re-implement the whole portal search algorithm? Isn't it possible to retrieve and validate target coordinates using the event?

**Comment by tastybento** [comment]
This is actually done already in 2.9.5. You can play test it now.

I've tried playing with the regular portal each algorithm and found it limited and sometimes random. In the end, it was better to run an async task to find the best location.
