### ISSUE TITLE
Add level-based generators for MagicCobbleGen

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#362]
Took from https://dev.bukkit.org/bukkit-plugins/skyblock/tickets/671-magic-cobble-generator-add-on/

**Comment by Poslovitch** [comment]
Please put in in 3.0.5 milestone ;) @tastybento

**Comment by Poslovitch** [comment]
To close ;)

**Comment by tastybento** [comment]
There were some bugs and I've been working to try and fix #368. I rewrote the generator to only change cobble blocks. It's not perfect, but I think it avoids the issues of #368. Other fixes are - the original code resulted in the same ore being generated all the time, and there wasn't a world check so it would happen in all worlds. I also changed to a treemap because that can give the level immediately rather than having to use a for loop to seach for it. Finally, I converted to Material. This all still needs more testing before closure.

**Comment by tastybento** [comment]
BTW, this doesn't work correctly yet - I think the treemap isn't working correctly, but I'm tired and I'll carry on tomorrow.

**Comment by Poslovitch** [comment]
I never used TreeMap... Interesting. I think I'll have a look on how does it work :)
I'm sorry but I can't help you 'til saturday.

Thanks for your work.

**Comment by tastybento** [comment]
Thank you! Let's do 3.0.5 testing now to make sure it's good enough to release.
