### ISSUE TITLE
Display Top 10 as an Hologram

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/askyblock#383]
The display place should be set by an admin command (e.g, /asadmin displaytop10).

It would display the top 10 as an Hologram (like this picture : goo.gl/lXUKAu )
Try to make it without using HolographicDisplayAPI (so would need a little NMS handling, but i think we could have a look on this class of a plugin i worked a little on : https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/holograms/ArmorStandFactory.java )

Should have an "auto-update" too ^^

And why do not "built-in" TopTenHeads in ASkyBlock?

**Comment by tastybento** [comment]
I would like to keep these as plugins to the plugin that use the API so that they don't have to be tested whenever there's a SW update. The plugin is quite big already and not everyone uses these features. However, I do love hologram things and so this might be good. I just don't want to add a lot of code if it can be done better as a plugin.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#48
