### ISSUE TITLE
Limit Diode [Redstone Repeater]

### ISSUE THREAD

**Issue by Fluxty** [tastybento/askyblock#444]
We have a global limit to the amount of devices that can pulse per second on our SkyBlock server. However, a single island is capable of hogging the entire limit by themselves using repeaters and timers with their cobble gens and what not. I was wondering if it was possible to limit the number of repeaters per island or maybe even the amount of redstone devices allowed to tick per second per island! We do use the newer offline redstone feature and it's been great.

This is what we use to limit global Redstone ticking and reduce clock rate (on 1.8.8):
https://www.spigotmc.org/resources/redstone-clock-preventer-2.6678/

**Comment by tastybento** [comment]
yes, the problem is quickly counting devices. With today's version, you can limit a redstone comparator and a few other devices, but that's it. Look for the **entitylimits:** around line 441 in the config.yml. Uncomment the REDSTONE_COMPARATOR. It's not the diode, but it may help.

Unfortunately, as we use a fast way to find these things, we're limited to tile entities and entities and a diode isn't one of them. However, it is entities that apparently cause lag, so maybe this will help.

**Comment by Fluxty** [comment]
Alright, yeah I understand. Repeater's do cause a bit of lag but I can see how counting them per island could cause issues as well. Maybe it is possible to listen for their ticking like RCP2 does (above) and limit per island, maybe I can do this with the API

**Comment by tastybento** [comment]
I had a look at the RCP2 code and it is really weird. I've no idea how it even works. There's really strange stuff in there. If you can work it out, I see there's a class in there to handle PoltSquared so it could possibly be changed to use the ASkyBlock API. Anyway, good luck!
