### ISSUE TITLE
Villager Eggs don't spawn villagers in 1.11.2

### ISSUE THREAD

**Issue by MonkvanNederland** [tastybento/askyblock#447]
server: paperspigot 1.11.2 build 1020
version: askyblock 3.0.5.3
config: https://hastebin.com/moxozehola.php
video: https://youtu.be/zJmxMYNJWm8

Since we updated to 1.11.2 villager spawn eggs don't spawn villagers. This only occurs on our Skyblock gamemode, which run the same base plugins except askyblock.jar.

There are no error or other messages. They simply do not spawn.

**Comment by tastybento** [comment]
I can't replicate this with a clean install test and the villagers can spawn fine. So, I think it's another plugin that is preventing it, especially because there is no error message. The simple test would be to stop the server, remove askyblock.jar, restart, login and then try to spawn villagers. I suspect you still won't be able to.
