### ISSUE TITLE
Chinese translation problem

### ISSUE THREAD

**Issue by berry64** [tastybento/askyblock#475]
![qq 20170124103524](https://cloud.githubusercontent.com/assets/10075321/22231874/e88951e2-e220-11e6-990a-2c109dc8ffbe.png)

this happens when I try to load the Chinese translation. possibly missing a few newly added messages? I can help translate if you can help me identify which messages are missing....

**Comment by berry64** [comment]
However, using /ai lang to switch locale is working and it doesn't log any errors

**Comment by tastybento** [comment]
How are you loading the Chinese translation? I'm away right now but this is a bug anyway. 

I should be very grateful if you could do an updated translation!

**Comment by berry64** [comment]
renaming the zh_CN.yml into locale.yml, maybe I should try to copy and paste it?

**Comment by tastybento** [comment]
It should work either way. I'm away right now but I'll look at it when I come back next week.

**Comment by tastybento** [comment]
Okay, this issue is caused by you having a file in your locale folder that has a name that doesn't fit the naming format of locale files. e.g., en-US.yml. It's most likely just got a short name of a few letters. The plugin should just ignore it so that's a bug. Quick fix - delete or move the file. I'll add code to fix this in the future - thanks!
