### ISSUE TITLE
Magic Cobble Gen information

### ISSUE THREAD

**Issue by RoyalRaid** [tastybento/askyblock#513]
I was wondering if you could give me some more information on how the Magic cobble gen works, My players have figured out some glitch where if they place water close to their auto cobble generators the chance of getting a rare ore decreases, yet if they place the water further back then they start to get more rare ores. It has stunned me so im hoping you can help haha

[http://prntscr.com/eaz4u3](url)
Here is a pic to kinda help you out, Basically the further the water source block is away from the generator the higher the chance you will get something rare

**Comment by tastybento** [comment]
The probabilities set in config.yml should be the best a player can possibly get. They may get worse than that because sometimes cobble is generated and the plugin cannot detect it (such is Minecraft...) 

So, your players may have optimized it, but they shouldn't be getting better than the settings. The way to confirm this is to do **/asadmin cobblestats** and see what is being generated. This is a running count. It should pretty much match the settings in config.yml that you have set. Note that in this version the stats are not kept separately for the different level settings, so if you use that feature, the results will be an average. I'll add level-specific stats to the next version.

Did you by chance adjust the cobble stat probabilities? Do the stats match?

**Comment by tastybento** [comment]
Improved by 0c41556 commit.

**Comment by RoyalRaid** [comment]
Awesome, rank the /asadmin cobblestats, They are quite similar to the config

**Comment by tastybento** [comment]
Okay, cool.
