### ISSUE TITLE
Is go bug, and asadmin spy is not working

### ISSUE THREAD

**Issue by fikry13** [tastybento/askyblock#52]
I try to use is go. when i save my home at y65 and i got another block on top of me on y75. And when i use is go, instead of going to y65 i was teleported to y75. Is this a bug?

asadmin spy is not working. I am using acid island btw. Tried acid spy, but not working too

**Comment by tastybento** [comment]
Q1: that sounds odd. It depends on what the block is at y65. If it's deemed unsafe then the plugin will try and find a safer place. Without seeing the actual block layout I can't guess why this would occur.

Q2. What happens when you do /asadmin spy? If it doesn't say "Team chat spy on" etc. then you need to check the following:

Check you are Op, or have the permission askyblock.mod.teamchatspy or acidisland.mod.teamchatspy.
Check that team chat is actually turned on in the config.yml.
Make sure that players are using it. I.e., they have switched on team chat.

**Comment by fikry13** [comment]
Q1: I would try to figure it myself. Thanks.

Q2: acidisland.mod.teamchatspy is already given. But the group is not OP, and it doesn't work. If OP was granted it works just fine.

**Comment by tastybento** [comment]
Okay I'll check Q2.

**Comment by tastybento** [comment]
There was a permission bug. acidisland.mod.spy needs to be given too as a permission. In V2.9.6, the official permission will be acidisland.mod.spy.
