### ISSUE TITLE
Question about island owner and abandoned island

### ISSUE THREAD

**Issue by SaitDev** [tastybento/askyblock#532]
Sorry to disturb while you are busy.

I got new created overlapped island after move my server from local pc to host provider. So i wonder about when a island be considered as abandoned island.
I try come to some old island, run `asadmin info` and get the message that the island isnt owned by anyone rightnow. The info about those island are still in `islands.yml` and about players in `ASkyBlock\players\` also in spawn world folder `world\playerdata\`

I've changed island's distance setting after few day testing server. Maybe it cause my problem?

**Comment by tastybento** [comment]
Changing island distance will alter the "grid" that the plugin uses to determine where islands are. That is most likely the root cause. Right now there's no way to have islands with different distances intermix. The new island algorithm will do a quick and dirty check for blocks to try to avoid structures in the world, but that's about it.
I recommend you set your island distance and keep it the same until you do a world reset.

**Comment by SaitDev** [comment]
Thank you. I tried purge all island instead of reset world cauz i wanna keep spawn point where i built shop. It seem ok now.
I will close this issue
