### ISSUE TITLE
ASkyBlock API - Island Level

### ISSUE THREAD

**Issue by LeoV117** [tastybento/askyblock#536]
I'm currently developing a plugin that needs to effect the level of an island.

Valuable blocks are "stacked", similar to Mob-Stacking, which reduces the amount of blocks that would be placed on an island.

I need a few pointers towards how to achieve the effect I'm trying to achieve.
That being, the island level would increase based on how many blocks of a specific type are stacked in place of one block.

**Comment by tastybento** [comment]
It sounds like you want to replace the current level calculation system - correct? In order to do that, you'd probably need some way for the current one to be cancelled and replaced/overridden by yours. That could possibly be done by me calling an event just before I do the calculation and allowing it to be done by your plugin. I'll look into offering that.

In terms of calculating blocks, it's something you need to do async otherwise your server will lag. What I do is copy chunk snapshots of the protected area of an island to a list and then pass that list to an async task to run through them and do the counting. You can look at the LevelCalcByChunk.java class for how I do it.

That actually means that when a player asks for a level calc, I don't force them to wait until the calculation is done. The result is sent to them after it's finished asynchronously. So after you have deduced the island level asynchronously, you need to tell the player and also update the island level for any team members.

Let's discuss more and I'll make this a feature request.

**Comment by LeoV117** [comment]
Either replace it, bypass it, or add to it.

Since it's such a small plugin, I don't see there being much need for a massive process to be altered.
However, if we can collaborate on the solution it would be appreciated.

**Comment by roastnewt** [comment]
This sounds like a fun idea to me - maybe an event that allows you to modify the island level before it is returned to the player?  It would allow cool stuff like taking other stats into account - player deaths, mobs killed, money balance (if you have an in-game economy), etc.  I would love to have that added to the API

**Comment by pjob97** [comment]
This would be an amazing feature, even just something as simple as during the island level calculation, it listens for any additional values to be added and/or subtracted from external plugins. The possibilities are nearly endless for adding dynamic features to the island level calculation, making it more meaningful than ever before.

I personally don't see the need for completely removing the current island level calculation system, just a simple addition / subtraction would do the trick.

**Comment by tastybento** [comment]
Done in commit 900140b50e86a44e1db3ed8ca48b4906c3bbf554
