### ISSUE TITLE
Posibility to set schematic generated to plots in the nether.

### ISSUE THREAD

**Issue by Foorack** [tastybento/askyblock#8]
Feature. Title describes itself. :-)

**Comment by xLRDx** [comment]
Oh i like this idea. So let me see if i understand. You want to have a schematic that is generated per player island when they first go to the nether? If so i really like this idea. Only issue i see is eventually you will get tons of these many spawns per say and they will all look the same. Wouldnt be a bad thing but a killer on the nether instead of just one little ole portal per player

**Comment by tastybento** [comment]
Done in 2.9.3, now in Master. Enjoy!
