### ISSUE TITLE
Issues with acidislands top ten

### ISSUE THREAD

**Issue by Charityss** [tastybento/askyblock#84]
I'm having a little problem with the top ten islands. For some reason none of my admins islands weren't showing in the top ten. I've just updated to V2.9.6.3 and now they're showing but my island still isn't. I've tried force updating it with /acid topten but I still can't seem to  get it to show up. I'm running spigot 1.8.8.

**Comment by tastybento** [comment]
It's because you are op and therefore automatically have the acidisland.mod.excludetopten permission (or maybe you have the acidisland.mod.* permission). Just give yourself the negative permission, e.g., do /pex user charityss add -acidisland.mod.excludetopten
That'll make you pop up on the top ten!

**Comment by Charityss** [comment]
Oh gosh I can't believe I didn't look for that before!!! Thank you so much and thanks for a quick response this plugin is awesome :)
